import 'package:flutter/material.dart';
import '../../core/constants/app_constants.dart';
import '../../core/models/contact_model.dart';

/// Dialog pour ajouter un nouveau contact d'urgence
class AddContactDialog extends StatefulWidget {
  final int priority;

  const AddContactDialog({
    super.key,
    required this.priority,
  });

  @override
  State<AddContactDialog> createState() => _AddContactDialogState();
}

class _AddContactDialogState extends State<AddContactDialog> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  String _selectedRelation = 'Famille';

  final List<String> _relations = [
    'Famille',
    'Ami(e)',
    'Collègue',
    'Voisin(e)',
    'Autre',
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  void _saveContact() {
    if (_formKey.currentState!.validate()) {
      final contact = ContactModel(
        id: '', // Will be generated by database
        utilisateurId: '', // Will be set by parent
        nom: _nameController.text.trim(),
        numeroTelephone: _phoneController.text.trim(),
        relation: _selectedRelation,
        priorite: widget.priority,
        actif: true,
        dateAjout: DateTime.now(),
      );

      Navigator.of(context).pop(contact);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(AppConstants.borderRadiusLarge),
      ),
      child: Padding(
        padding: const EdgeInsets.all(AppConstants.paddingLarge),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // En-tête
              Row(
                children: [
                  Container(
                    width: 40,
                    height: 40,
                    decoration: const BoxDecoration(
                      color: AppConstants.primaryColor,
                      shape: BoxShape.circle,
                    ),
                    child: Center(
                      child: Text(
                        '${widget.priority}',
                        style: const TextStyle(
                          color: AppConstants.whiteColor,
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: AppConstants.spacingMedium),
                  const Expanded(
                    child: Text(
                      'Nouveau Contact d\'Urgence',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: AppConstants.primaryColor,
                      ),
                    ),
                  ),
                ],
              ),
              
              const SizedBox(height: AppConstants.spacingLarge),
              
              // Champ nom
              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(
                  labelText: 'Nom complet *',
                  prefixIcon: Icon(Icons.person),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Le nom est requis';
                  }
                  if (value.trim().length < 2) {
                    return 'Le nom doit contenir au moins 2 caractères';
                  }
                  return null;
                },
              ),
              
              const SizedBox(height: AppConstants.spacingMedium),
              
              // Champ téléphone
              TextFormField(
                controller: _phoneController,
                decoration: const InputDecoration(
                  labelText: 'Numéro de téléphone *',
                  prefixIcon: Icon(Icons.phone),
                  hintText: '+224 XXX XX XX XX',
                ),
                keyboardType: TextInputType.phone,
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Le numéro de téléphone est requis';
                  }
                  final cleanNumber = value.replaceAll(RegExp(r'[^\d+]'), '');
                  if (cleanNumber.length < 8) {
                    return 'Numéro de téléphone invalide';
                  }
                  return null;
                },
              ),
              
              const SizedBox(height: AppConstants.spacingMedium),
              
              // Sélection de la relation
              DropdownButtonFormField<String>(
                value: _selectedRelation,
                decoration: const InputDecoration(
                  labelText: 'Relation',
                  prefixIcon: Icon(Icons.group),
                ),
                items: _relations.map((relation) {
                  return DropdownMenuItem(
                    value: relation,
                    child: Text(relation),
                  );
                }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _selectedRelation = value;
                    });
                  }
                },
              ),
              
              const SizedBox(height: AppConstants.spacingMedium),
              
              // Information de priorité
              Container(
                padding: const EdgeInsets.all(AppConstants.paddingSmall),
                decoration: BoxDecoration(
                  color: AppConstants.primaryColor.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(AppConstants.borderRadiusMedium),
                ),
                child: Row(
                  children: [
                    const Icon(
                      Icons.info_outline,
                      color: AppConstants.primaryColor,
                      size: 16,
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Ce contact sera alerté en priorité ${widget.priority} lors d\'une urgence.',
                        style: const TextStyle(
                          fontSize: 12,
                          color: AppConstants.primaryColor,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
              
              const SizedBox(height: AppConstants.spacingLarge),
              
              // Boutons d'action
              Row(
                children: [
                  Expanded(
                    child: TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: const Text('Annuler'),
                    ),
                  ),
                  const SizedBox(width: AppConstants.spacingMedium),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _saveContact,
                      child: const Text('Ajouter'),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
